// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimoProgettoBlazor.Components.Classi;

#nullable disable

namespace PrimoProgettoBlazor.Migrations
{
    [DbContext(typeof(BancaDati))]
    [Migration("20251219075101_Prima")]
    partial class Prima
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.Abilità", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAbilità")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abilità");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.AbilitàPersonaggio", b =>
                {
                    b.Property<int>("AbilitàIdAbilità")
                        .HasColumnType("int");

                    b.Property<int>("PersonaggioId")
                        .HasColumnType("int");

                    b.Property<int>("AbilitàId")
                        .HasColumnType("int");

                    b.Property<int>("Punteggio")
                        .HasColumnType("int");

                    b.HasKey("AbilitàIdAbilità", "PersonaggioId");

                    b.HasIndex("AbilitàId");

                    b.HasIndex("PersonaggioId");

                    b.ToTable("AbilitàPersonaggi");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.Attacco", b =>
                {
                    b.Property<int>("IdAttacco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAttacco"));

                    b.Property<int>("Moltiplicatore")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaggioId")
                        .HasColumnType("int");

                    b.Property<int>("Roll")
                        .HasColumnType("int");

                    b.Property<string>("Vigore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAttacco");

                    b.HasIndex("PersonaggioId");

                    b.ToTable("Attacchi");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.Giocatore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Giocatori");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.Personaggio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Armatura")
                        .HasColumnType("int");

                    b.Property<int>("GiocatoreId")
                        .HasColumnType("int");

                    b.Property<string>("Iniziativa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LivelloMinaccia")
                        .HasColumnType("int");

                    b.Property<string>("ModifAttacco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salute")
                        .HasColumnType("int");

                    b.Property<int>("SessioneId")
                        .HasColumnType("int");

                    b.Property<string>("TiroColpire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiroDifesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vigore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiocatoreId");

                    b.HasIndex("SessioneId");

                    b.ToTable("Personaggi");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.Sessione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessioni");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.AbilitàPersonaggio", b =>
                {
                    b.HasOne("PrimoProgettoBlazor.Components.Classi.Entities.Abilità", "Abilità")
                        .WithMany("Personaggi")
                        .HasForeignKey("AbilitàId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimoProgettoBlazor.Components.Classi.Entities.Personaggio", "Personaggio")
                        .WithMany("Abilità")
                        .HasForeignKey("PersonaggioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abilità");

                    b.Navigation("Personaggio");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.Attacco", b =>
                {
                    b.HasOne("PrimoProgettoBlazor.Components.Classi.Entities.Personaggio", "Personaggio")
                        .WithMany("Attacchi")
                        .HasForeignKey("PersonaggioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaggio");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.Personaggio", b =>
                {
                    b.HasOne("PrimoProgettoBlazor.Components.Classi.Entities.Giocatore", "Giocatore")
                        .WithMany("Personaggi")
                        .HasForeignKey("GiocatoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimoProgettoBlazor.Components.Classi.Entities.Sessione", "Sessione")
                        .WithMany("Personaggi")
                        .HasForeignKey("SessioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Giocatore");

                    b.Navigation("Sessione");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.Abilità", b =>
                {
                    b.Navigation("Personaggi");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.Giocatore", b =>
                {
                    b.Navigation("Personaggi");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.Personaggio", b =>
                {
                    b.Navigation("Abilità");

                    b.Navigation("Attacchi");
                });

            modelBuilder.Entity("PrimoProgettoBlazor.Components.Classi.Entities.Sessione", b =>
                {
                    b.Navigation("Personaggi");
                });
#pragma warning restore 612, 618
        }
    }
}
